version: '3.9'

services:
  postgres:
    image: postgres:alpine3.20
    container_name: parkir_postgres
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_DB: parkir_pintar
      POSTGRES_USER: parkir
      POSTGRES_PASSWORD: parkir
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local

  redis:
    image: redis:alpine
    container_name: parkir_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    networks:
      - local

  nats:
    image: nats:latest
    container_name: parkir_nats
    ports:
      - "4222:4222"   # NATS client connections
      - "8222:8222"   # NATS monitoring interface
      - "6222:6222"   # NATS clustering port
    command: ["-js"]  # Enables JetStream
    volumes:
      - nats_data:/data
    environment:
      - NATS_MAX_MEMORY=2GB
      - NATS_MAX_PAYLOAD=64MB
    restart: always
    networks:
      - local

  reservation-service:
    container_name: parkir_reservation
    build:
      context: ./reservation
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./configs/reservation/.env.docker
    depends_on:
      - postgres
      - redis
      - nats
    restart: always
    networks:
      - local

  search-service:
    container_name: parkir_search
    build:
      context: ./search
      dockerfile: Dockerfile
    ports:
      - "8083:8082"
    env_file:
      - ./configs/search/.env.docker
    depends_on:
      - postgres
    restart: always
    networks:
      - local

  presence-service:
    container_name: parkir_presence
    build:
      context: ./presence
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    env_file:
      - ./configs/presence/.env.docker
    depends_on:
      - postgres
    restart: always
    networks:
      - local

  billing-service:
    container_name: parkir_billing
    build:
      context: ./billing
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    env_file:
      - ./configs/billing/.env.docker
    depends_on:
      - postgres
      - nats
    restart: always
    networks:
      - local

  payment-service:
    container_name: parkir_payment
    build:
      context: ./payment
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
      - "8087:8087"
    env_file:
      - ./configs/payment/.env.docker
    depends_on:
      - postgres
      - nats
    restart: always
    networks:
      - local

  payment-gateway:
    container_name: parkir_payment_gateway
    build:
      context: ./stubs/payment-gateway
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    env_file:
      - ./stubs/payment-gateway/.env.docker
    depends_on:
      - payment-service
    restart: always
    networks:
      - local

  notification-service:
    container_name: parkir_notification
    build:
      context: ./stubs/notification
      dockerfile: Dockerfile
    env_file:
      - ./stubs/notification/.env.docker
    depends_on:
      - nats
    restart: always
    networks:
      - local

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  nats_data:
    driver: local

networks:
  local:
