sonar.projectKey=ermasavior_ParkirPintar-search
sonar.organization=ermasavior

sonar.exclusions=deployments/**/*,Makefile,_mock/**/*,**/pkg/**/*.go,cmd/**/*.go,db/**/*,proto/**/*,gen/**/*
sonar.test.inclusions=**/*_test.go