// Code generated by MockGen. DO NOT EDIT.
// Source: internal/search/usecase/init.go
//
// Generated by this command:
//
//	mockgen -source=internal/search/usecase/init.go -destination=_mock/search/mock_usecase.go -package=mocksearch -mock_names=Search=MockSearchUsecase
//

// Package mocksearch is a generated GoMock package.
package mocksearch

import (
	context "context"
	model "parkir-pintar/services/search/internal/search/model"
	apperror "parkir-pintar/services/search/pkg/apperror"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSearchUsecase is a mock of Search interface.
type MockSearchUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockSearchUsecaseMockRecorder
	isgomock struct{}
}

// MockSearchUsecaseMockRecorder is the mock recorder for MockSearchUsecase.
type MockSearchUsecaseMockRecorder struct {
	mock *MockSearchUsecase
}

// NewMockSearchUsecase creates a new mock instance.
func NewMockSearchUsecase(ctrl *gomock.Controller) *MockSearchUsecase {
	mock := &MockSearchUsecase{ctrl: ctrl}
	mock.recorder = &MockSearchUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchUsecase) EXPECT() *MockSearchUsecaseMockRecorder {
	return m.recorder
}

// GetAvailability mocks base method.
func (m *MockSearchUsecase) GetAvailability(ctx context.Context, req model.GetAvailabilityRequest) (*model.GetAvailabilityResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailability", ctx, req)
	ret0, _ := ret[0].(*model.GetAvailabilityResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetAvailability indicates an expected call of GetAvailability.
func (mr *MockSearchUsecaseMockRecorder) GetAvailability(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailability", reflect.TypeOf((*MockSearchUsecase)(nil).GetAvailability), ctx, req)
}

// ListSpots mocks base method.
func (m *MockSearchUsecase) ListSpots(ctx context.Context, req model.ListSpotsRequest) (*model.ListSpotsResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSpots", ctx, req)
	ret0, _ := ret[0].(*model.ListSpotsResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// ListSpots indicates an expected call of ListSpots.
func (mr *MockSearchUsecaseMockRecorder) ListSpots(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSpots", reflect.TypeOf((*MockSearchUsecase)(nil).ListSpots), ctx, req)
}
